#mdh axone k8s deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abi-fe
  namespace: spryt-dev
  labels:
    app: abi-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abi-fe
  template:
    metadata:
      labels:
        app: abi-fe
    spec:
      serviceAccountName: abi-fe
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - name: abi-fe
        image: europe-west2-docker.pkg.dev/asa-dev-442913/sprytacrdev/abi-fe:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: abi-fe-env-configmap
        - secretRef:
            name: abi-fe-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "768Mi"
            cpu: "400m"