const dev = {
  API_ENDPOINT_URL: import.meta.env.VITE_APP_API_URL,
  SOCKETS_DOMAIN: import.meta.env.VITE_APP_SOCKETS_DOMAIN,
  SOCKETS_NOTIFICATION_DOMAIN: import.meta.env.VITE_APP_SOCKETS_NOTIFICATION_DOMAIN,
  URL_PREFIX_PATH: import.meta.env.VITE_APP_URL_PREFIX_PATH,
  SHOW_APPOINTMENTS_LIKELY_TO_BE_MISSED:
    import.meta.env.VITE_APP_SHOW_APPOINTMENTS_LIKELY_TO_BE_MISSED,
  SHOW_PASSED_APPOINTMENTS_REQUIRING_IMMEDIATE_ATTENTION:
    import.meta.env
      .VITE_APP_SHOW_PASSED_APPOINTMENTS_REQUIRING_IMMEDIATE_ATTENTION,
  SHOW_MESSAGES_REQUIRING_IMMEDIATE_ATTENTION:
    import.meta.env.VITE_APP_SHOW_MESSAGES_REQUIRING_IMMEDIATE_ATTENTION,
  SHOW_APPOINTMENTS_REMINDERS:
    import.meta.env.VITE_APP_SHOW_APPOINTMENTS_REMINDERS,
  SHOW_KPIS: import.meta.env.VITE_APP_SHOW_KPIS,
  SHOW_PATIENT_PROGRESS: import.meta.env.VITE_APP_SHOW_PATIENT_PROGRESS,
  CAPTCHA_CLIENT_KEY_V2: import.meta.env.VITE_APP_CAPTCHA_CLIENT_KEY_V2,
};

const prod = {
  API_ENDPOINT_URL: import.meta.env.VITE_APP_API_URL,
  SOCKETS_DOMAIN: import.meta.env.VITE_APP_SOCKETS_DOMAIN,
  SOCKETS_NOTIFICATION_DOMAIN: import.meta.env.VITE_APP_SOCKETS_NOTIFICATION_DOMAIN,
  URL_PREFIX_PATH: import.meta.env.VITE_APP_URL_PREFIX_PATH,
  SHOW_APPOINTMENTS_LIKELY_TO_BE_MISSED:
    import.meta.env.VITE_APP_SHOW_APPOINTMENTS_LIKELY_TO_BE_MISSED,
  SHOW_PASSED_APPOINTMENTS_REQUIRING_IMMEDIATE_ATTENTION:
    import.meta.env
      .VITE_APP_SHOW_PASSED_APPOINTMENTS_REQUIRING_IMMEDIATE_ATTENTION,
  SHOW_MESSAGES_REQUIRING_IMMEDIATE_ATTENTION:
    import.meta.env.VITE_APP_SHOW_MESSAGES_REQUIRING_IMMEDIATE_ATTENTION,
  SHOW_APPOINTMENTS_REMINDERS:
    import.meta.env.VITE_APP_SHOW_APPOINTMENTS_REMINDERS,
  SHOW_KPIS: import.meta.env.VITE_APP_SHOW_KPIS,
  SHOW_PATIENT_PROGRESS: import.meta.env.VITE_APP_SHOW_PATIENT_PROGRESS,
  CAPTCHA_CLIENT_KEY_V2: import.meta.env.VITE_APP_CAPTCHA_CLIENT_KEY_V2,
};

const test = {
  API_ENDPOINT_URL: import.meta.env.VITE_APP_API_URL,
  SOCKETS_DOMAIN: import.meta.env.VITE_APP_SOCKETS_DOMAIN,
  SOCKETS_NOTIFICATION_DOMAIN: import.meta.env.VITE_APP_SOCKETS_NOTIFICATION_DOMAIN,
  URL_PREFIX_PATH: import.meta.env.VITE_APP_URL_PREFIX_PATH,
  SHOW_APPOINTMENTS_LIKELY_TO_BE_MISSED:
    import.meta.env.VITE_APP_SHOW_APPOINTMENTS_LIKELY_TO_BE_MISSED,
  SHOW_PASSED_APPOINTMENTS_REQUIRING_IMMEDIATE_ATTENTION:
    import.meta.env
      .VITE_APP_SHOW_PASSED_APPOINTMENTS_REQUIRING_IMMEDIATE_ATTENTION,
  SHOW_MESSAGES_REQUIRING_IMMEDIATE_ATTENTION:
    import.meta.env.VITE_APP_SHOW_MESSAGES_REQUIRING_IMMEDIATE_ATTENTION,
  SHOW_APPOINTMENTS_REMINDERS:
    import.meta.env.VITE_APP_SHOW_APPOINTMENTS_REMINDERS,
  SHOW_KPIS: import.meta.env.VITE_APP_SHOW_KPIS,
  SHOW_PATIENT_PROGRESS: import.meta.env.VITE_APP_SHOW_PATIENT_PROGRESS,
  CAPTCHA_CLIENT_KEY_V2: import.meta.env.VITE_APP_CAPTCHA_CLIENT_KEY_V2,
};

const getEnv = () => {
  switch (import.meta.env.MODE) {
    case 'development':
      return dev;
    case 'production':
      return prod;
    case 'test':
      return test;
    default:
      break;
  }
};

export const env = getEnv();
