#mdh axone k8s deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abi-fe
  namespace: spryt-prod
  labels:
    app: abi-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abi-fe
  template:
    metadata:
      labels:
        app: abi-fe
    spec:
      containers:
      - name: abi-fe
        image: sprytacrprod.azurecr.io/abi-fe
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: abi-fe-env-configmap
        resources:
          requests:
            memory: "1024Mi"
            cpu: "330m"
          limits:
            memory: "1024Mi"
            cpu: "330m"