## abi-fe K8S INGRESSES
# abi-fe k8s Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abi-fe-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: abi-fe-nginx-ingress
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: abi-fe-service
            port:
              number: 80

---

## abi-fe K8S SERVICES
# abi-fe k8s service
apiVersion: v1
kind: Service
metadata:
  name: abi-fe-service
  namespace: production
  labels:
    app: abi-fe
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: abi-fe