apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: abi-fe-secrets
  namespace: spryt-test
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/asa-test-438109/secrets/VITE_APP_CAPTCHA_CLIENT_KEY_V2/versions/latest"
        path: "VITE_APP_CAPTCHA_CLIENT_KEY_V2"
