apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: abi-fe-secrets
  namespace: spryt-test
spec:
  serviceAccountName: abi-fe
  secretProviderClassName: abi-fe-secrets
  secretObject:
    type: Opaque
    data:
      - sourcePath: "CAPTCHA_CLIENT_KEY_V2"
        targetKey: "VITE_APP_CAPTCHA_CLIENT_KEY_V2"
