apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: abi-fe-secrets
  namespace: production
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/spryt-medbridge/secrets/CAPTCHA_CLIENT_KEY_V2/versions/latest"
        path: "CAPTCHA_CLIENT_KEY_V2"
