export const GET_MEDICAL_CONDITIONS = 'GET_MEDICAL_CONDITIONS';
export const SET_MEDICAL_CONDITIONS = 'SET_MEDICAL_CONDITIONS';
export const GET_PREVIOUS_OPERATIONS = 'GET_PREVIOUS_OPERATIONS';
export const SET_PREVIOUS_OPERATIONS = 'SET_PREVIOUS_OPERATIONS';
export const SET_ANEMNESIS_LOADING = 'SET_ANEMNESIS_LOADING';
export const SET_ANEMNESIS_PAGE = 'SET_ANEMNESIS_PAGE';
