export const GET_MEDICAL_CONDITIONS = 'GET_MEDICAL_CONDITIONS';
export const SET_MEDICAL_CONDITIONS = 'SET_MEDICAL_CONDITIONS';
export const GET_PREVIOUS_OPERATIONS = 'GET_PREVIOUS_OPERATIONS';
export const SET_PREVIOUS_OPERATIONS = 'SET_PREVIOUS_OPERATIONS';
export const SET_ANEMNESIS_LOADING = 'SET_ANEMNESIS_LOADING';
export const SET_ANEMNESIS_PAGE = 'SET_ANEMNESIS_PAGE';
export const CREATE_MEDICAL_CONDITION = 'CREATE_MEDICAL_CONDITION';
export const DELETE_MEDICAL_CONDITION = 'DELETE_MEDICAL_CONDITION';
export const RESET_EXISTING_MEDICAL_CONDITION =
  'RESET_EXISTING_MEDICAL_CONDITION';
