export const SET_DOCTOR_APPOINTMENTS = 'SET_DOCTOR_APPOINTMENTS';
export const GET_DOCTOR_APPOINTMENTS = 'GET_DOCTOR_APPOINTMENTS';
export const SET_DATE_APPOINTMENTS = 'SET_DATE_APPOINTMENTS';
export const GET_DATE_APPOINTMENTS = 'GET_DATE_APPOINTMENTS';
export const SET_IS_LOADING = 'SET_APPOINTMENTS_IS_LOADING';
