export const SET_DOCTOR_APPOINTMENTS = 'SET_DOCTOR_APPOINTMENTS';
export const GET_DOCTOR_APPOINTMENTS = 'GET_DOCTOR_APPOINTMENTS';
export const SET_DATE_APPOINTMENTS = 'SET_DATE_APPOINTMENTS';
export const GET_DATE_APPOINTMENTS = 'GET_DATE_APPOINTMENTS';
export const SET_IS_LOADING = 'SET_APPOINTMENTS_IS_LOADING';
export const SET_SINGLE_APPOINTMENT = 'SET_SINGLE_APPOINTMENT';
export const GET_SINGLE_APPOINTMENT = 'GET_SINGLE_APPOINTMENT';
export const SET_SINGLE_APPOINTMENT_LOADING = 'SET_SINGLE_APPOINTMENT_LOADING';
