export const SET_INTVALID_OLD_PASSWORD_ERROR =
  'SET_INTVALID_OLD_PASSWORD_ERROR';

export const SET_CREATE_CLINIC_ERROR = 'SET_CREATE_CLINIC_ERROR';
export const SET_CLINIC_ERROR = 'SET_CLINIC_ERROR';
