export const UPDATED_INDUSTRY_AVERAGE = 'UPDATED_INDUSTRY_AVERAGE';
export const UPDATED_INDUSTRY_AVERAGE_ERROR = 'UPDATED_INDUSTRY_AVERAGE_ERROR';
export const UPDATED_INDUSTRY_AVERAGE_SUCCESS =
  'UPDATED_INDUSTRY_AVERAGE_SUCCESS';

export const GET_INDUSTRY_AVERAGE = 'GET_INDUSTRY_AVERAGE';
export const GET_INDUSTRY_AVERAGE_SUCCESS = 'GET_INDUSTRY_AVERAGE_SUCCESS';
export const GET_INDUSTRY_AVERAGE_ERROR = 'GET_INDUSTRY_AVERAGE_ERROR';

export const SET_LOADING = 'SET_LOADING';
