export const SET_OVERVIEW_SUMMARY_DATA = 'SET_OVERVIEW_SUMMARY_DATA';
export const GET_OVERVIEW_SUMMARY_DATA = 'GET_OVERVIEW_SUMMARY_DATA';
export const GET_OVERVIEW_CLINICSTATS_DATA = 'GET_OVERVIEW_CLINICSTATS_DATA';
export const SET_OVERVIEW_CLINICSTATS_DATA = 'SET_OVERVIEW_CLINICSTATS_DATA';
export const SET_OVERVIEW_CLINICSTATS_DATA_LOADING =
  'SET_OVERVIEW_CLINICSTATS_DATA_LOADING';
export const SET_OVERVIEW_SUMMARY_DATA_LOADING =
  'SET_OVERVIEW_SUMMARY_DATA_LOADING';
