export const SET_OVERVIEW_SUMMARY_DATA = 'SET_OVERVIEW_SUMMARY_DATA';
export const GET_OVERVIEW_SUMMARY_DATA = 'GET_OVERVIEW_SUMMARY_DATA';
export const GET_OVERVIEW_CLINICSTATS_DATA = 'GET_OVERVIEW_CLINICSTATS_DATA';
export const SET_OVERVIEW_CLINICSTATS_DATA = 'SET_OVERVIEW_CLINICSTATS_DATA';
export const SET_OVERVIEW_CLINICSTATS_DATA_LOADING =
  'SET_OVERVIEW_CLINICSTATS_DATA_LOADING';
export const SET_OVERVIEW_SUMMARY_DATA_LOADING =
  'SET_OVERVIEW_SUMMARY_DATA_LOADING';

export const SET_OVERVIEW_KPI_FUNNEL_LOADING = 'SET_OVERVIEW_KPI_FUNNEL_LOADING';
export const SET_OVERVIEW_KPI_BOOKING_LOADING = 'SET_OVERVIEW_KPI_BOOKING_LOADING';
export const SET_OVERVIEW_KPI_INTERVENTIONS_LOADING =
  'SET_OVERVIEW_KPI_INTERVENTIONS_LOADING';
export const SET_OVERVIEW_KPI_FUNNEL_DATA = 'SET_OVERVIEW_KPI_FUNNEL_DATA';
export const SET_OVERVIEW_KPI_BOOKING_DATA = 'SET_OVERVIEW_KPI_BOOKING_DATA';
export const SET_OVERVIEW_KPI_INTERVENTIONS_DATA =
  'SET_OVERVIEW_KPI_INTERVENTIONS_DATA';
