export const GET_PATIENTS = 'GET_PATIENTS';
export const SET_PATIENTS = 'SET_PATIENTS';
export const GET_PATIENTS_DETAILS = 'GET_PATIENTS_DETAILS';
export const SET_PATIENT_PAGE = 'SET_PATIENT_PAGE';
export const SET_PATIENT_LOADING = 'SET_PATIENT_LOADING';
export const SET_PATIENT_ORDER = 'SET_PATIENT_ORDER';
export const SET_PATIENT_SEARCH = 'SET_PATIENT_SEARCH';
export const DELETE_PATIENT = 'DELETE_PATIENT';
