export const GET_STAFF = 'GET_STAFF';
export const SET_STAFF = 'SET_STAFF';
export const SET_STAFF_PAGE = 'SET_STAFF_PAGE';
export const SET_STAFF_LOADING = 'SET_STAFF_LOADING';
export const SET_STAFF_DETAILS = 'SET_STAFF_DETAILS';
export const GET_STAFF_DETAILS = 'GET_STAFF_DETAILS';
export const CREATE_STAFF = 'CREATE_STAFF';
export const UPDATE_STAFF = 'UPDATE_STAFF';
export const GET_STAFF_SINGLE = 'GET_STAFF_SINGLE';
export const SET_STAFF_SINGLE = 'SET_STAFF_SINGLE';
export const DELTETE_STAFF = 'DELTETE_STAFF';
export const GET_STAFF_APPOINTMENTS = 'GET_STAFF_APPOINTMENTS';
export const SET_STAFF_APPOINTMENTS = 'SET_STAFF_APPOINTMENTS';
export const SET_STAFF_APPOINTMENTS_PAGE = 'SET_STAFF_APPOINTMENTS_PAGE';
export const SET_STAFF_APPOINTMENTS_LOADING = 'SET_STAFF_APPOINTMENTS_LOADING';
export const SET_STAFF_APPOINTMENTS_ORDER = 'SET_STAFF_APPOINTMENTS_ORDER';
export const SET_SCHEDULED_STAFF_APPOINTMENTS_PAGE =
  'SET_SCHEDULED_STAFF_APPOINTMENTS_PAGE';
export const SET_PAST_STAFF_APPOINTMENTS_PAGE =
  'SET_PAST_STAFF_APPOINTMENTS_PAGE';
